[project]
name = "qa-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.1.40",
    "langchain-google-genai>=2.1.4",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
]
